//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biz.dfch.CS.CoffeeTracker.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("biz.dfch.CS.CoffeeTracker.Core.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start remove {0} with Id: {1} 
        /// {2}.
        /// </summary>
        internal static string Delete_Entity_Start {
            get {
                return ResourceManager.GetString("Delete_Entity_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with id {1} Removed.
        /// </summary>
        internal static string Delete_Entity_Stop {
            get {
                return ResourceManager.GetString("Delete_Entity_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good day,&lt;br&gt;
        ///&lt;br&gt;
        /// A coffee is about/ran out of stock. Consider to refill stock.&lt;br&gt; 
        /// Coffee Name: &lt;blockquote&gt;{0}&lt;/blockquote&gt; 
        /// Coffee Brand: &lt;blockquote&gt;{1}&lt;/blockquote&gt; 
        ///&lt;br&gt;
        /// Regards&lt;br&gt; 
        ///&lt;br&gt;
        /// The CoffeeTracker Api.
        /// </summary>
        internal static string EmailManager_CreateAndSendOutOfStockEmail_ {
            get {
                return ResourceManager.GetString("EmailManager_CreateAndSendOutOfStockEmail_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get {0}s.
        /// </summary>
        internal static string Get_Entities {
            get {
                return ResourceManager.GetString("Get_Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get {0} with Id: {1}.
        /// </summary>
        internal static string Get_Entity {
            get {
                return ResourceManager.GetString("Get_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Insert {0}: 
        /// {1}....
        /// </summary>
        internal static string Insert_Entity_Start {
            get {
                return ResourceManager.GetString("Insert_Entity_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert {0} finished. EntityId: {1}.
        /// </summary>
        internal static string Insert_Entity_Stop {
            get {
                return ResourceManager.GetString("Insert_Entity_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Update {0} with Id: {1}....
        /// </summary>
        internal static string Update_Entity_Patch_Start {
            get {
                return ResourceManager.GetString("Update_Entity_Patch_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop modifiedCoffee {0} with Id: {1} 
        /// {2}.
        /// </summary>
        internal static string Update_Entity_Patch_Stop {
            get {
                return ResourceManager.GetString("Update_Entity_Patch_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Update of {0} with id {1}....
        /// </summary>
        internal static string Update_Entity_Put_Start {
            get {
                return ResourceManager.GetString("Update_Entity_Put_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with id {1} modifiedCoffeed. entity: 
        /// {2}.
        /// </summary>
        internal static string Update_Entity_Put_Stop {
            get {
                return ResourceManager.GetString("Update_Entity_Put_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply {0} config....
        /// </summary>
        internal static string WebApiConfig_Register__Start {
            get {
                return ResourceManager.GetString("WebApiConfig_Register__Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply {0} config SUCCEEDED.
        /// </summary>
        internal static string WebApiConfig_Register__SUCCEEDED {
            get {
                return ResourceManager.GetString("WebApiConfig_Register__SUCCEEDED", resourceCulture);
            }
        }
    }
}
