// <auto-generated />
namespace biz.dfch.CS.CoffeeTracker.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AdjustedUserAddedCoffeeAndCoffeeOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdjustedUserAddedCoffeeAndCoffeeOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201701181007437_AdjustedUserAddedCoffeeAndCoffeeOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
