//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 28-Mar-17 08:35:58
namespace biz.dfch.CS.CoffeeTracker.Client.CoffeeTrackerService
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Microsoft.AspNet.Identity.EntityFramework", "biz.dfch.CS.CoffeeTracker.Client.CoffeeTrackerService.Microsoft.AspNet.Identity.E" +
                    "ntityFramework");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "biz.dfch.CS.CoffeeTracker.Core.Model", "biz.dfch.CS.CoffeeTracker.Client.CoffeeTrackerService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("biz.dfch.CS.CoffeeTracker.Client.CoffeeTrackerService.Microsoft.AspNet.Identity.E" +
                    "ntityFramework", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Microsoft.AspNet.Identity.EntityFramework.", clientType.Name);
            }
            if (clientType.Namespace.Equals("biz.dfch.CS.CoffeeTracker.Client.CoffeeTrackerService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("biz.dfch.CS.CoffeeTracker.Core.Model.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ApplicationUser> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<ApplicationUser>("Users");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ApplicationUser> _Users;
        /// <summary>
        /// There are no comments for IdentityUsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<biz.dfch.CS.CoffeeTracker.Client.CoffeeTrackerService.Microsoft.AspNet.Identity.EntityFramework.IdentityUser> IdentityUsers
        {
            get
            {
                if ((this._IdentityUsers == null))
                {
                    this._IdentityUsers = base.CreateQuery<biz.dfch.CS.CoffeeTracker.Client.CoffeeTrackerService.Microsoft.AspNet.Identity.EntityFramework.IdentityUser>("IdentityUsers");
                }
                return this._IdentityUsers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<biz.dfch.CS.CoffeeTracker.Client.CoffeeTrackerService.Microsoft.AspNet.Identity.EntityFramework.IdentityUser> _IdentityUsers;
        /// <summary>
        /// There are no comments for Coffees in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Coffee> Coffees
        {
            get
            {
                if ((this._Coffees == null))
                {
                    this._Coffees = base.CreateQuery<Coffee>("Coffees");
                }
                return this._Coffees;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Coffee> _Coffees;
        /// <summary>
        /// There are no comments for CoffeeOrders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CoffeeOrder> CoffeeOrders
        {
            get
            {
                if ((this._CoffeeOrders == null))
                {
                    this._CoffeeOrders = base.CreateQuery<CoffeeOrder>("CoffeeOrders");
                }
                return this._CoffeeOrders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CoffeeOrder> _CoffeeOrders;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsers(ApplicationUser applicationUser)
        {
            base.AddObject("Users", applicationUser);
        }
        /// <summary>
        /// There are no comments for IdentityUsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToIdentityUsers(biz.dfch.CS.CoffeeTracker.Client.CoffeeTrackerService.Microsoft.AspNet.Identity.EntityFramework.IdentityUser identityUser)
        {
            base.AddObject("IdentityUsers", identityUser);
        }
        /// <summary>
        /// There are no comments for Coffees in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCoffees(Coffee coffee)
        {
            base.AddObject("Coffees", coffee);
        }
        /// <summary>
        /// There are no comments for CoffeeOrders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCoffeeOrders(CoffeeOrder coffeeOrder)
        {
            base.AddObject("CoffeeOrders", coffeeOrder);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"biz.dfch.CS.CoffeeTracker.Core.Model\" xmlns=\"http://schemas.microsoft" +
                ".com/ado/2009/11/edm\"><EntityType Name=\"ApplicationUser\"><Key><PropertyRef Name=" +
                "\"Id\" /></Key><Property Name=\"Password\" Type=\"Edm.String\" Nullable=\"false\" /><Pro" +
                "perty Name=\"AspNetUserId\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"I" +
                "sAdmin\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"Id\" Type=\"Edm.Int6" +
                "4\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" /" +
                "><NavigationProperty Name=\"CorrespondingAspNetUser\" Relationship=\"Microsoft.AspN" +
                "et.Identity.EntityFramework.biz_dfch_CS_CoffeeTracker_Core_Model_ApplicationUser" +
                "_CorrespondingAspNetUser_Microsoft_AspNet_Identity_EntityFramework_IdentityUser_" +
                "CorrespondingAspNetUserPartner\" ToRole=\"CorrespondingAspNetUser\" FromRole=\"Corre" +
                "spondingAspNetUserPartner\" /></EntityType><EntityType Name=\"Coffee\"><Key><Proper" +
                "tyRef Name=\"Id\" /></Key><Property Name=\"Brand\" Type=\"Edm.String\" Nullable=\"false" +
                "\" /><Property Name=\"Price\" Type=\"Edm.Decimal\" Nullable=\"false\" /><Property Name=" +
                "\"Stock\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"LastDelivery\" Type=\"" +
                "Edm.DateTimeOffset\" Nullable=\"false\" /><Property Name=\"Id\" Type=\"Edm.Int64\" Null" +
                "able=\"false\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" /></Enti" +
                "tyType><EntityType Name=\"CoffeeOrder\"><Key><PropertyRef Name=\"Id\" /></Key><Prope" +
                "rty Name=\"UserId\" Type=\"Edm.Int64\" Nullable=\"false\" /><Property Name=\"CoffeeId\" " +
                "Type=\"Edm.Int64\" Nullable=\"false\" /><Property Name=\"Created\" Type=\"Edm.DateTimeO" +
                "ffset\" Nullable=\"false\" /><Property Name=\"Id\" Type=\"Edm.Int64\" Nullable=\"false\" " +
                "/><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" /><NavigationProperty" +
                " Name=\"ApplicationUser\" Relationship=\"biz.dfch.CS.CoffeeTracker.Core.Model.biz_d" +
                "fch_CS_CoffeeTracker_Core_Model_CoffeeOrder_ApplicationUser_biz_dfch_CS_CoffeeTr" +
                "acker_Core_Model_ApplicationUser_ApplicationUserPartner\" ToRole=\"ApplicationUser" +
                "\" FromRole=\"ApplicationUserPartner\" /><NavigationProperty Name=\"Coffee\" Relation" +
                "ship=\"biz.dfch.CS.CoffeeTracker.Core.Model.biz_dfch_CS_CoffeeTracker_Core_Model_" +
                "CoffeeOrder_Coffee_biz_dfch_CS_CoffeeTracker_Core_Model_Coffee_CoffeePartner\" To" +
                "Role=\"Coffee\" FromRole=\"CoffeePartner\" /></EntityType><Association Name=\"biz_dfc" +
                "h_CS_CoffeeTracker_Core_Model_CoffeeOrder_ApplicationUser_biz_dfch_CS_CoffeeTrac" +
                "ker_Core_Model_ApplicationUser_ApplicationUserPartner\"><End Type=\"biz.dfch.CS.Co" +
                "ffeeTracker.Core.Model.ApplicationUser\" Role=\"ApplicationUser\" Multiplicity=\"0.." +
                "1\" /><End Type=\"biz.dfch.CS.CoffeeTracker.Core.Model.CoffeeOrder\" Role=\"Applicat" +
                "ionUserPartner\" Multiplicity=\"0..1\" /><ReferentialConstraint><Principal Role=\"Ap" +
                "plicationUser\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"Application" +
                "UserPartner\"><PropertyRef Name=\"UserId\" /></Dependent></ReferentialConstraint></" +
                "Association><Association Name=\"biz_dfch_CS_CoffeeTracker_Core_Model_CoffeeOrder_" +
                "Coffee_biz_dfch_CS_CoffeeTracker_Core_Model_Coffee_CoffeePartner\"><End Type=\"biz" +
                ".dfch.CS.CoffeeTracker.Core.Model.Coffee\" Role=\"Coffee\" Multiplicity=\"0..1\" /><E" +
                "nd Type=\"biz.dfch.CS.CoffeeTracker.Core.Model.CoffeeOrder\" Role=\"CoffeePartner\" " +
                "Multiplicity=\"0..1\" /><ReferentialConstraint><Principal Role=\"Coffee\"><PropertyR" +
                "ef Name=\"Id\" /></Principal><Dependent Role=\"CoffeePartner\"><PropertyRef Name=\"Co" +
                "ffeeId\" /></Dependent></ReferentialConstraint></Association></Schema><Schema Nam" +
                "espace=\"Microsoft.AspNet.Identity.EntityFramework\" xmlns=\"http://schemas.microso" +
                "ft.com/ado/2009/11/edm\"><EntityType Name=\"IdentityUser\"><Key><PropertyRef Name=\"" +
                "Id\" /></Key><Property Name=\"Email\" Type=\"Edm.String\" /><Property Name=\"EmailConf" +
                "irmed\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"PasswordHash\" Type=" +
                "\"Edm.String\" /><Property Name=\"SecurityStamp\" Type=\"Edm.String\" /><Property Name" +
                "=\"PhoneNumber\" Type=\"Edm.String\" /><Property Name=\"PhoneNumberConfirmed\" Type=\"E" +
                "dm.Boolean\" Nullable=\"false\" /><Property Name=\"TwoFactorEnabled\" Type=\"Edm.Boole" +
                "an\" Nullable=\"false\" /><Property Name=\"LockoutEndDateUtc\" Type=\"Edm.DateTime\" />" +
                "<Property Name=\"LockoutEnabled\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property " +
                "Name=\"AccessFailedCount\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Rol" +
                "es\" Type=\"Collection(Microsoft.AspNet.Identity.EntityFramework.IdentityUserRole)" +
                "\" Nullable=\"false\" /><Property Name=\"Logins\" Type=\"Collection(Microsoft.AspNet.I" +
                "dentity.EntityFramework.IdentityUserLogin)\" Nullable=\"false\" /><Property Name=\"I" +
                "d\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"UserName\" Type=\"Edm.Stri" +
                "ng\" /><NavigationProperty Name=\"Claims\" Relationship=\"Microsoft.AspNet.Identity." +
                "EntityFramework.Microsoft_AspNet_Identity_EntityFramework_IdentityUser_Claims_Mi" +
                "crosoft_AspNet_Identity_EntityFramework_IdentityUserClaim_ClaimsPartner\" ToRole=" +
                "\"Claims\" FromRole=\"ClaimsPartner\" /></EntityType><ComplexType Name=\"IdentityUser" +
                "Role\"><Property Name=\"UserId\" Type=\"Edm.String\" /><Property Name=\"RoleId\" Type=\"" +
                "Edm.String\" /></ComplexType><EntityType Name=\"IdentityUserClaim\"><Key><PropertyR" +
                "ef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Pr" +
                "operty Name=\"UserId\" Type=\"Edm.String\" /><Property Name=\"ClaimType\" Type=\"Edm.St" +
                "ring\" /><Property Name=\"ClaimValue\" Type=\"Edm.String\" /></EntityType><ComplexTyp" +
                "e Name=\"IdentityUserLogin\"><Property Name=\"LoginProvider\" Type=\"Edm.String\" /><P" +
                "roperty Name=\"ProviderKey\" Type=\"Edm.String\" /><Property Name=\"UserId\" Type=\"Edm" +
                ".String\" /></ComplexType><Association Name=\"biz_dfch_CS_CoffeeTracker_Core_Model" +
                "_ApplicationUser_CorrespondingAspNetUser_Microsoft_AspNet_Identity_EntityFramewo" +
                "rk_IdentityUser_CorrespondingAspNetUserPartner\"><End Type=\"Microsoft.AspNet.Iden" +
                "tity.EntityFramework.IdentityUser\" Role=\"CorrespondingAspNetUser\" Multiplicity=\"" +
                "0..1\" /><End Type=\"biz.dfch.CS.CoffeeTracker.Core.Model.ApplicationUser\" Role=\"C" +
                "orrespondingAspNetUserPartner\" Multiplicity=\"0..1\" /><ReferentialConstraint><Pri" +
                "ncipal Role=\"CorrespondingAspNetUser\"><PropertyRef Name=\"Id\" /></Principal><Depe" +
                "ndent Role=\"CorrespondingAspNetUserPartner\"><PropertyRef Name=\"AspNetUserId\" /><" +
                "/Dependent></ReferentialConstraint></Association><Association Name=\"Microsoft_As" +
                "pNet_Identity_EntityFramework_IdentityUser_Claims_Microsoft_AspNet_Identity_Enti" +
                "tyFramework_IdentityUserClaim_ClaimsPartner\"><End Type=\"Microsoft.AspNet.Identit" +
                "y.EntityFramework.IdentityUserClaim\" Role=\"Claims\" Multiplicity=\"*\" /><End Type=" +
                "\"Microsoft.AspNet.Identity.EntityFramework.IdentityUser\" Role=\"ClaimsPartner\" Mu" +
                "ltiplicity=\"0..1\" /></Association></Schema><Schema Namespace=\"Default\" xmlns=\"ht" +
                "tp://schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"Container\" m:" +
                "IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Users\" EntityType=\"biz.dfch.CS." +
                "CoffeeTracker.Core.Model.ApplicationUser\" /><EntitySet Name=\"IdentityUsers\" Enti" +
                "tyType=\"Microsoft.AspNet.Identity.EntityFramework.IdentityUser\" /><EntitySet Nam" +
                "e=\"Coffees\" EntityType=\"biz.dfch.CS.CoffeeTracker.Core.Model.Coffee\" /><EntitySe" +
                "t Name=\"CoffeeOrders\" EntityType=\"biz.dfch.CS.CoffeeTracker.Core.Model.CoffeeOrd" +
                "er\" /><FunctionImport Name=\"GetCoffeeConsumptionByCurrentUser\" ReturnType=\"Edm.I" +
                "nt32\" IsBindable=\"true\" m:IsAlwaysBindable=\"true\"><Parameter Name=\"bindingParame" +
                "ter\" Type=\"Collection(biz.dfch.CS.CoffeeTracker.Core.Model.CoffeeOrder)\" Nullabl" +
                "e=\"false\" /><Parameter Name=\"From\" Type=\"Edm.DateTimeOffset";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "\" Nullable=\"false\" /><Parameter Name=\"Until\" Type=\"Edm.DateTimeOffset\" Nullable=\"" +
                "false\" /></FunctionImport><FunctionImport Name=\"GetCoffeeConsumption\" ReturnType" +
                "=\"Edm.Int32\" IsBindable=\"true\" m:IsAlwaysBindable=\"true\"><Parameter Name=\"bindin" +
                "gParameter\" Type=\"Collection(biz.dfch.CS.CoffeeTracker.Core.Model.CoffeeOrder)\" " +
                "Nullable=\"false\" /><Parameter Name=\"From\" Type=\"Edm.DateTimeOffset\" Nullable=\"fa" +
                "lse\" /><Parameter Name=\"Until\" Type=\"Edm.DateTimeOffset\" Nullable=\"false\" /></Fu" +
                "nctionImport><FunctionImport Name=\"GetCoffeeConsumptionByCoffee\" ReturnType=\"Edm" +
                ".Int32\" IsBindable=\"true\" m:IsAlwaysBindable=\"true\"><Parameter Name=\"bindingPara" +
                "meter\" Type=\"Collection(biz.dfch.CS.CoffeeTracker.Core.Model.CoffeeOrder)\" Nulla" +
                "ble=\"false\" /><Parameter Name=\"Name\" Type=\"Edm.String\" FixedLength=\"false\" Unico" +
                "de=\"false\" /><Parameter Name=\"Brand\" Type=\"Edm.String\" FixedLength=\"false\" Unico" +
                "de=\"false\" /><Parameter Name=\"From\" Type=\"Edm.DateTimeOffset\" Nullable=\"false\" /" +
                "><Parameter Name=\"Until\" Type=\"Edm.DateTimeOffset\" Nullable=\"false\" /></Function" +
                "Import><FunctionImport Name=\"GetMostOrderedCoffee\" ReturnType=\"biz.dfch.CS.Coffe" +
                "eTracker.Core.Model.Coffee\" IsBindable=\"true\" EntitySet=\"Coffees\" m:IsAlwaysBind" +
                "able=\"true\"><Parameter Name=\"bindingParameter\" Type=\"Collection(biz.dfch.CS.Coff" +
                "eeTracker.Core.Model.CoffeeOrder)\" Nullable=\"false\" /><Parameter Name=\"From\" Typ" +
                "e=\"Edm.DateTimeOffset\" Nullable=\"false\" /><Parameter Name=\"Until\" Type=\"Edm.Date" +
                "TimeOffset\" Nullable=\"false\" /></FunctionImport><FunctionImport Name=\"GetMostOrd" +
                "eredCoffeeByUser\" ReturnType=\"biz.dfch.CS.CoffeeTracker.Core.Model.Coffee\" IsBin" +
                "dable=\"true\" EntitySet=\"Coffees\" m:IsAlwaysBindable=\"true\"><Parameter Name=\"bind" +
                "ingParameter\" Type=\"Collection(biz.dfch.CS.CoffeeTracker.Core.Model.CoffeeOrder)" +
                "\" Nullable=\"false\" /><Parameter Name=\"From\" Type=\"Edm.DateTimeOffset\" Nullable=\"" +
                "false\" /><Parameter Name=\"Until\" Type=\"Edm.DateTimeOffset\" Nullable=\"false\" /><P" +
                "arameter Name=\"Email\" Type=\"Edm.String\" FixedLength=\"false\" Unicode=\"false\" /></" +
                "FunctionImport><AssociationSet Name=\"biz_dfch_CS_CoffeeTracker_Core_Model_Applic" +
                "ationUser_CorrespondingAspNetUser_Microsoft_AspNet_Identity_EntityFramework_Iden" +
                "tityUser_CorrespondingAspNetUserPartnerSet\" Association=\"Microsoft.AspNet.Identi" +
                "ty.EntityFramework.biz_dfch_CS_CoffeeTracker_Core_Model_ApplicationUser_Correspo" +
                "ndingAspNetUser_Microsoft_AspNet_Identity_EntityFramework_IdentityUser_Correspon" +
                "dingAspNetUserPartner\"><End Role=\"CorrespondingAspNetUserPartner\" EntitySet=\"Use" +
                "rs\" /><End Role=\"CorrespondingAspNetUser\" EntitySet=\"IdentityUsers\" /></Associat" +
                "ionSet><AssociationSet Name=\"biz_dfch_CS_CoffeeTracker_Core_Model_CoffeeOrder_Ap" +
                "plicationUser_biz_dfch_CS_CoffeeTracker_Core_Model_ApplicationUser_ApplicationUs" +
                "erPartnerSet\" Association=\"biz.dfch.CS.CoffeeTracker.Core.Model.biz_dfch_CS_Coff" +
                "eeTracker_Core_Model_CoffeeOrder_ApplicationUser_biz_dfch_CS_CoffeeTracker_Core_" +
                "Model_ApplicationUser_ApplicationUserPartner\"><End Role=\"ApplicationUserPartner\"" +
                " EntitySet=\"CoffeeOrders\" /><End Role=\"ApplicationUser\" EntitySet=\"Users\" /></As" +
                "sociationSet><AssociationSet Name=\"biz_dfch_CS_CoffeeTracker_Core_Model_CoffeeOr" +
                "der_Coffee_biz_dfch_CS_CoffeeTracker_Core_Model_Coffee_CoffeePartnerSet\" Associa" +
                "tion=\"biz.dfch.CS.CoffeeTracker.Core.Model.biz_dfch_CS_CoffeeTracker_Core_Model_" +
                "CoffeeOrder_Coffee_biz_dfch_CS_CoffeeTracker_Core_Model_Coffee_CoffeePartner\"><E" +
                "nd Role=\"CoffeePartner\" EntitySet=\"CoffeeOrders\" /><End Role=\"Coffee\" EntitySet=" +
                "\"Coffees\" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></ed" +
                "mx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for biz.dfch.CS.CoffeeTracker.Core.Model.ApplicationUser in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Users")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ApplicationUser : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ApplicationUser object.
        /// </summary>
        /// <param name="password">Initial value of Password.</param>
        /// <param name="aspNetUserId">Initial value of AspNetUserId.</param>
        /// <param name="isAdmin">Initial value of IsAdmin.</param>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ApplicationUser CreateApplicationUser(string password, string aspNetUserId, bool isAdmin, long ID, string name)
        {
            ApplicationUser applicationUser = new ApplicationUser();
            applicationUser.Password = password;
            applicationUser.AspNetUserId = aspNetUserId;
            applicationUser.IsAdmin = isAdmin;
            applicationUser.Id = ID;
            applicationUser.Name = name;
            return applicationUser;
        }
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property AspNetUserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AspNetUserId
        {
            get
            {
                return this._AspNetUserId;
            }
            set
            {
                this.OnAspNetUserIdChanging(value);
                this._AspNetUserId = value;
                this.OnAspNetUserIdChanged();
                this.OnPropertyChanged("AspNetUserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AspNetUserId;
        partial void OnAspNetUserIdChanging(string value);
        partial void OnAspNetUserIdChanged();
        /// <summary>
        /// There are no comments for Property IsAdmin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsAdmin
        {
            get
            {
                return this._IsAdmin;
            }
            set
            {
                this.OnIsAdminChanging(value);
                this._IsAdmin = value;
                this.OnIsAdminChanged();
                this.OnPropertyChanged("IsAdmin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsAdmin;
        partial void OnIsAdminChanging(bool value);
        partial void OnIsAdminChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for CorrespondingAspNetUser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public biz.dfch.CS.CoffeeTracker.Client.CoffeeTrackerService.Microsoft.AspNet.Identity.EntityFramework.IdentityUser CorrespondingAspNetUser
        {
            get
            {
                return this._CorrespondingAspNetUser;
            }
            set
            {
                this._CorrespondingAspNetUser = value;
                this.OnPropertyChanged("CorrespondingAspNetUser");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private biz.dfch.CS.CoffeeTracker.Client.CoffeeTrackerService.Microsoft.AspNet.Identity.EntityFramework.IdentityUser _CorrespondingAspNetUser;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for biz.dfch.CS.CoffeeTracker.Core.Model.Coffee in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Coffees")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Coffee : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Coffee object.
        /// </summary>
        /// <param name="brand">Initial value of Brand.</param>
        /// <param name="price">Initial value of Price.</param>
        /// <param name="stock">Initial value of Stock.</param>
        /// <param name="lastDelivery">Initial value of LastDelivery.</param>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Coffee CreateCoffee(string brand, decimal price, int stock, global::System.DateTimeOffset lastDelivery, long ID, string name)
        {
            Coffee coffee = new Coffee();
            coffee.Brand = brand;
            coffee.Price = price;
            coffee.Stock = stock;
            coffee.LastDelivery = lastDelivery;
            coffee.Id = ID;
            coffee.Name = name;
            return coffee;
        }
        /// <summary>
        /// There are no comments for Property Brand in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Brand
        {
            get
            {
                return this._Brand;
            }
            set
            {
                this.OnBrandChanging(value);
                this._Brand = value;
                this.OnBrandChanged();
                this.OnPropertyChanged("Brand");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Brand;
        partial void OnBrandChanging(string value);
        partial void OnBrandChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
                this.OnPropertyChanged("Price");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Price;
        partial void OnPriceChanging(decimal value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property Stock in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Stock
        {
            get
            {
                return this._Stock;
            }
            set
            {
                this.OnStockChanging(value);
                this._Stock = value;
                this.OnStockChanged();
                this.OnPropertyChanged("Stock");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Stock;
        partial void OnStockChanging(int value);
        partial void OnStockChanged();
        /// <summary>
        /// There are no comments for Property LastDelivery in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTimeOffset LastDelivery
        {
            get
            {
                return this._LastDelivery;
            }
            set
            {
                this.OnLastDeliveryChanging(value);
                this._LastDelivery = value;
                this.OnLastDeliveryChanged();
                this.OnPropertyChanged("LastDelivery");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTimeOffset _LastDelivery;
        partial void OnLastDeliveryChanging(global::System.DateTimeOffset value);
        partial void OnLastDeliveryChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for biz.dfch.CS.CoffeeTracker.Core.Model.CoffeeOrder in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CoffeeOrders")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class CoffeeOrder : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CoffeeOrder object.
        /// </summary>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="coffeeId">Initial value of CoffeeId.</param>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CoffeeOrder CreateCoffeeOrder(long userId, long coffeeId, global::System.DateTimeOffset created, long ID, string name)
        {
            CoffeeOrder coffeeOrder = new CoffeeOrder();
            coffeeOrder.UserId = userId;
            coffeeOrder.CoffeeId = coffeeId;
            coffeeOrder.Created = created;
            coffeeOrder.Id = ID;
            coffeeOrder.Name = name;
            return coffeeOrder;
        }
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _UserId;
        partial void OnUserIdChanging(long value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property CoffeeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long CoffeeId
        {
            get
            {
                return this._CoffeeId;
            }
            set
            {
                this.OnCoffeeIdChanging(value);
                this._CoffeeId = value;
                this.OnCoffeeIdChanged();
                this.OnPropertyChanged("CoffeeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _CoffeeId;
        partial void OnCoffeeIdChanging(long value);
        partial void OnCoffeeIdChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTimeOffset Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTimeOffset _Created;
        partial void OnCreatedChanging(global::System.DateTimeOffset value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for ApplicationUser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationUser ApplicationUser
        {
            get
            {
                return this._ApplicationUser;
            }
            set
            {
                this._ApplicationUser = value;
                this.OnPropertyChanged("ApplicationUser");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ApplicationUser _ApplicationUser;
        /// <summary>
        /// There are no comments for Coffee in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Coffee Coffee
        {
            get
            {
                return this._Coffee;
            }
            set
            {
                this._Coffee = value;
                this.OnPropertyChanged("Coffee");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Coffee _Coffee;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
// Original file name:
// Generation date: 28-Mar-17 08:35:59
namespace biz.dfch.CS.CoffeeTracker.Client.CoffeeTrackerService.Microsoft.AspNet.Identity.EntityFramework
{
    
    /// <summary>
    /// There are no comments for ComplexType Microsoft.AspNet.Identity.EntityFramework.IdentityUserRole in the schema.
    /// </summary>
    public partial class IdentityUserRole : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserId;
        partial void OnUserIdChanging(string value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property RoleId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RoleId
        {
            get
            {
                return this._RoleId;
            }
            set
            {
                this.OnRoleIdChanging(value);
                this._RoleId = value;
                this.OnRoleIdChanged();
                this.OnPropertyChanged("RoleId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RoleId;
        partial void OnRoleIdChanging(string value);
        partial void OnRoleIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType Microsoft.AspNet.Identity.EntityFramework.IdentityUserLogin in the schema.
    /// </summary>
    public partial class IdentityUserLogin : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property LoginProvider in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LoginProvider
        {
            get
            {
                return this._LoginProvider;
            }
            set
            {
                this.OnLoginProviderChanging(value);
                this._LoginProvider = value;
                this.OnLoginProviderChanged();
                this.OnPropertyChanged("LoginProvider");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LoginProvider;
        partial void OnLoginProviderChanging(string value);
        partial void OnLoginProviderChanged();
        /// <summary>
        /// There are no comments for Property ProviderKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProviderKey
        {
            get
            {
                return this._ProviderKey;
            }
            set
            {
                this.OnProviderKeyChanging(value);
                this._ProviderKey = value;
                this.OnProviderKeyChanged();
                this.OnPropertyChanged("ProviderKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProviderKey;
        partial void OnProviderKeyChanging(string value);
        partial void OnProviderKeyChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserId;
        partial void OnUserIdChanging(string value);
        partial void OnUserIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Microsoft.AspNet.Identity.EntityFramework.IdentityUser in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("IdentityUsers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class IdentityUser : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new IdentityUser object.
        /// </summary>
        /// <param name="emailConfirmed">Initial value of EmailConfirmed.</param>
        /// <param name="phoneNumberConfirmed">Initial value of PhoneNumberConfirmed.</param>
        /// <param name="twoFactorEnabled">Initial value of TwoFactorEnabled.</param>
        /// <param name="lockoutEnabled">Initial value of LockoutEnabled.</param>
        /// <param name="accessFailedCount">Initial value of AccessFailedCount.</param>
        /// <param name="roles">Initial value of Roles.</param>
        /// <param name="logins">Initial value of Logins.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static IdentityUser CreateIdentityUser(bool emailConfirmed, bool phoneNumberConfirmed, bool twoFactorEnabled, bool lockoutEnabled, int accessFailedCount, global::System.Collections.ObjectModel.ObservableCollection<IdentityUserRole> roles, global::System.Collections.ObjectModel.ObservableCollection<IdentityUserLogin> logins, string ID)
        {
            IdentityUser identityUser = new IdentityUser();
            identityUser.EmailConfirmed = emailConfirmed;
            identityUser.PhoneNumberConfirmed = phoneNumberConfirmed;
            identityUser.TwoFactorEnabled = twoFactorEnabled;
            identityUser.LockoutEnabled = lockoutEnabled;
            identityUser.AccessFailedCount = accessFailedCount;
            if ((roles == null))
            {
                throw new global::System.ArgumentNullException("roles");
            }
            identityUser.Roles = roles;
            if ((logins == null))
            {
                throw new global::System.ArgumentNullException("logins");
            }
            identityUser.Logins = logins;
            identityUser.Id = ID;
            return identityUser;
        }
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property EmailConfirmed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool EmailConfirmed
        {
            get
            {
                return this._EmailConfirmed;
            }
            set
            {
                this.OnEmailConfirmedChanging(value);
                this._EmailConfirmed = value;
                this.OnEmailConfirmedChanged();
                this.OnPropertyChanged("EmailConfirmed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _EmailConfirmed;
        partial void OnEmailConfirmedChanging(bool value);
        partial void OnEmailConfirmedChanged();
        /// <summary>
        /// There are no comments for Property PasswordHash in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PasswordHash
        {
            get
            {
                return this._PasswordHash;
            }
            set
            {
                this.OnPasswordHashChanging(value);
                this._PasswordHash = value;
                this.OnPasswordHashChanged();
                this.OnPropertyChanged("PasswordHash");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PasswordHash;
        partial void OnPasswordHashChanging(string value);
        partial void OnPasswordHashChanged();
        /// <summary>
        /// There are no comments for Property SecurityStamp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SecurityStamp
        {
            get
            {
                return this._SecurityStamp;
            }
            set
            {
                this.OnSecurityStampChanging(value);
                this._SecurityStamp = value;
                this.OnSecurityStampChanged();
                this.OnPropertyChanged("SecurityStamp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SecurityStamp;
        partial void OnSecurityStampChanging(string value);
        partial void OnSecurityStampChanged();
        /// <summary>
        /// There are no comments for Property PhoneNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PhoneNumber
        {
            get
            {
                return this._PhoneNumber;
            }
            set
            {
                this.OnPhoneNumberChanging(value);
                this._PhoneNumber = value;
                this.OnPhoneNumberChanged();
                this.OnPropertyChanged("PhoneNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PhoneNumber;
        partial void OnPhoneNumberChanging(string value);
        partial void OnPhoneNumberChanged();
        /// <summary>
        /// There are no comments for Property PhoneNumberConfirmed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool PhoneNumberConfirmed
        {
            get
            {
                return this._PhoneNumberConfirmed;
            }
            set
            {
                this.OnPhoneNumberConfirmedChanging(value);
                this._PhoneNumberConfirmed = value;
                this.OnPhoneNumberConfirmedChanged();
                this.OnPropertyChanged("PhoneNumberConfirmed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _PhoneNumberConfirmed;
        partial void OnPhoneNumberConfirmedChanging(bool value);
        partial void OnPhoneNumberConfirmedChanged();
        /// <summary>
        /// There are no comments for Property TwoFactorEnabled in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool TwoFactorEnabled
        {
            get
            {
                return this._TwoFactorEnabled;
            }
            set
            {
                this.OnTwoFactorEnabledChanging(value);
                this._TwoFactorEnabled = value;
                this.OnTwoFactorEnabledChanged();
                this.OnPropertyChanged("TwoFactorEnabled");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _TwoFactorEnabled;
        partial void OnTwoFactorEnabledChanging(bool value);
        partial void OnTwoFactorEnabledChanged();
        /// <summary>
        /// There are no comments for Property LockoutEndDateUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> LockoutEndDateUtc
        {
            get
            {
                return this._LockoutEndDateUtc;
            }
            set
            {
                this.OnLockoutEndDateUtcChanging(value);
                this._LockoutEndDateUtc = value;
                this.OnLockoutEndDateUtcChanged();
                this.OnPropertyChanged("LockoutEndDateUtc");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _LockoutEndDateUtc;
        partial void OnLockoutEndDateUtcChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLockoutEndDateUtcChanged();
        /// <summary>
        /// There are no comments for Property LockoutEnabled in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool LockoutEnabled
        {
            get
            {
                return this._LockoutEnabled;
            }
            set
            {
                this.OnLockoutEnabledChanging(value);
                this._LockoutEnabled = value;
                this.OnLockoutEnabledChanged();
                this.OnPropertyChanged("LockoutEnabled");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _LockoutEnabled;
        partial void OnLockoutEnabledChanging(bool value);
        partial void OnLockoutEnabledChanged();
        /// <summary>
        /// There are no comments for Property AccessFailedCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AccessFailedCount
        {
            get
            {
                return this._AccessFailedCount;
            }
            set
            {
                this.OnAccessFailedCountChanging(value);
                this._AccessFailedCount = value;
                this.OnAccessFailedCountChanged();
                this.OnPropertyChanged("AccessFailedCount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AccessFailedCount;
        partial void OnAccessFailedCountChanging(int value);
        partial void OnAccessFailedCountChanged();
        /// <summary>
        /// There are no comments for Property Roles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.ObservableCollection<IdentityUserRole> Roles
        {
            get
            {
                return this._Roles;
            }
            set
            {
                this.OnRolesChanging(value);
                this._Roles = value;
                this.OnRolesChanged();
                this.OnPropertyChanged("Roles");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<IdentityUserRole> _Roles = new global::System.Collections.ObjectModel.ObservableCollection<IdentityUserRole>();
        partial void OnRolesChanging(global::System.Collections.ObjectModel.ObservableCollection<IdentityUserRole> value);
        partial void OnRolesChanged();
        /// <summary>
        /// There are no comments for Property Logins in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.ObservableCollection<IdentityUserLogin> Logins
        {
            get
            {
                return this._Logins;
            }
            set
            {
                this.OnLoginsChanging(value);
                this._Logins = value;
                this.OnLoginsChanged();
                this.OnPropertyChanged("Logins");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<IdentityUserLogin> _Logins = new global::System.Collections.ObjectModel.ObservableCollection<IdentityUserLogin>();
        partial void OnLoginsChanging(global::System.Collections.ObjectModel.ObservableCollection<IdentityUserLogin> value);
        partial void OnLoginsChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
                this.OnPropertyChanged("UserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Claims in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<IdentityUserClaim> Claims
        {
            get
            {
                return this._Claims;
            }
            set
            {
                this._Claims = value;
                this.OnPropertyChanged("Claims");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<IdentityUserClaim> _Claims = new global::System.Data.Services.Client.DataServiceCollection<IdentityUserClaim>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Microsoft.AspNet.Identity.EntityFramework.IdentityUserClaim in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class IdentityUserClaim : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new IdentityUserClaim object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static IdentityUserClaim CreateIdentityUserClaim(int ID)
        {
            IdentityUserClaim identityUserClaim = new IdentityUserClaim();
            identityUserClaim.Id = ID;
            return identityUserClaim;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserId;
        partial void OnUserIdChanging(string value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property ClaimType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ClaimType
        {
            get
            {
                return this._ClaimType;
            }
            set
            {
                this.OnClaimTypeChanging(value);
                this._ClaimType = value;
                this.OnClaimTypeChanged();
                this.OnPropertyChanged("ClaimType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ClaimType;
        partial void OnClaimTypeChanging(string value);
        partial void OnClaimTypeChanged();
        /// <summary>
        /// There are no comments for Property ClaimValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ClaimValue
        {
            get
            {
                return this._ClaimValue;
            }
            set
            {
                this.OnClaimValueChanging(value);
                this._ClaimValue = value;
                this.OnClaimValueChanged();
                this.OnPropertyChanged("ClaimValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ClaimValue;
        partial void OnClaimValueChanging(string value);
        partial void OnClaimValueChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
