//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biz.dfch.CS.CoffeeTracker.Client.Wpf.Resources.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("biz.dfch.CS.CoffeeTracker.Client.Wpf.Resources.LanguageResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Button_Login {
            get {
                return ResourceManager.GetString("Login_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create one!.
        /// </summary>
        public static string Login_Label_CreateOne {
            get {
                return ResourceManager.GetString("Login_Label_CreateOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Login_Label_EmailAddress {
            get {
                return ResourceManager.GetString("Login_Label_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have an account?.
        /// </summary>
        public static string Login_Label_NoAccount {
            get {
                return ResourceManager.GetString("Login_Label_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Label_Password {
            get {
                return ResourceManager.GetString("Login_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account was successfully created.
        /// </summary>
        public static string Login_TextBox_CreatedAccount {
            get {
                return ResourceManager.GetString("Login_TextBox_CreatedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email/password cimbination.
        /// </summary>
        public static string Login_TextBox_InvalidCredentials {
            get {
                return ResourceManager.GetString("Login_TextBox_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoffeeTracker - Login.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string Registration_Button_Create {
            get {
                return ResourceManager.GetString("Registration_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Have an account?.
        /// </summary>
        public static string Registration_Label_AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("Registration_Label_AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the Login page.
        /// </summary>
        public static string Registration_Label_GoToLogin {
            get {
                return ResourceManager.GetString("Registration_Label_GoToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Could not create account.
        /// </summary>
        public static string Registration_RegistrationFailed {
            get {
                return ResourceManager.GetString("Registration_RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration_Title {
            get {
                return ResourceManager.GetString("Registration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password again.
        /// </summary>
        public static string Registration_Tooltip_ReEnterPassword {
            get {
                return ResourceManager.GetString("Registration_Tooltip_ReEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email@example.com.
        /// </summary>
        public static string Shared_Email_Example {
            get {
                return ResourceManager.GetString("Shared_Email_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ******.
        /// </summary>
        public static string Shared_Password_Example {
            get {
                return ResourceManager.GetString("Shared_Password_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Email address.
        /// </summary>
        public static string UserControl_EmailLabeledTextBox_EnterValidMail {
            get {
                return ResourceManager.GetString("UserControl_EmailLabeledTextBox_EnterValidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password which contains at least 6 characters.
        /// </summary>
        public static string UserControl_PasswordLabeledPasswordBox_ValidPassword {
            get {
                return ResourceManager.GetString("UserControl_PasswordLabeledPasswordBox_ValidPassword", resourceCulture);
            }
        }
    }
}
