//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biz.dfch.CS.CoffeeTracker.Client.Wpf.Resources.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("biz.dfch.CS.CoffeeTracker.Client.Wpf.Resources.LanguageResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoffeeOrder.
        /// </summary>
        public static string BaseWindow_SideBar_CoffeeOrder {
            get {
                return ResourceManager.GetString("BaseWindow_SideBar_CoffeeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffees.
        /// </summary>
        public static string BaseWindow_SideBar_Coffees {
            get {
                return ResourceManager.GetString("BaseWindow_SideBar_Coffees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string BaseWindow_SideBar_Home {
            get {
                return ResourceManager.GetString("BaseWindow_SideBar_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string BaseWindow_SideBar_Logout {
            get {
                return ResourceManager.GetString("BaseWindow_SideBar_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string BaseWindow_SideBar_Statistics {
            get {
                return ResourceManager.GetString("BaseWindow_SideBar_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoffeeOrders.
        /// </summary>
        public static string CoffeeOrders_Title {
            get {
                return ResourceManager.GetString("CoffeeOrders_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Coffees_Label_Brand {
            get {
                return ResourceManager.GetString("Coffees_Label_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Delivery.
        /// </summary>
        public static string Coffees_Label_LastDelivery {
            get {
                return ResourceManager.GetString("Coffees_Label_LastDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Coffees_Label_Name {
            get {
                return ResourceManager.GetString("Coffees_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Coffees_Label_Price {
            get {
                return ResourceManager.GetString("Coffees_Label_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Coffees_Label_Stock {
            get {
                return ResourceManager.GetString("Coffees_Label_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffees.
        /// </summary>
        public static string Coffees_Title {
            get {
                return ResourceManager.GetString("Coffees_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Coffee.
        /// </summary>
        public static string CoffeesSelector_Label_SelectCoffee {
            get {
                return ResourceManager.GetString("CoffeesSelector_Label_SelectCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string DetermineTimePicker_From {
            get {
                return ResourceManager.GetString("DetermineTimePicker_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        public static string DetermineTimePicker_Until {
            get {
                return ResourceManager.GetString("DetermineTimePicker_Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Email address.
        /// </summary>
        public static string EmailLabeledTextBox_ToolTip_EnterValidMail {
            get {
                return ResourceManager.GetString("EmailLabeledTextBox_ToolTip_EnterValidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Coffee.
        /// </summary>
        public static string Home_Label_AddOrder {
            get {
                return ResourceManager.GetString("Home_Label_AddOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your coffee has been successfully ordered.
        /// </summary>
        public static string Home_Label_CoffeeOrderPlaced {
            get {
                return ResourceManager.GetString("Home_Label_CoffeeOrderPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected coffee is out of stock.
        /// </summary>
        public static string Home_Label_CoffeeOutOfStock {
            get {
                return ResourceManager.GetString("Home_Label_CoffeeOutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating the order.
        /// </summary>
        public static string Home_Label_CouldntPlaceOrder {
            get {
                return ResourceManager.GetString("Home_Label_CouldntPlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on Stock:.
        /// </summary>
        public static string Home_Label_OnStock {
            get {
                return ResourceManager.GetString("Home_Label_OnStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        public static string Home_Label_Price {
            get {
                return ResourceManager.GetString("Home_Label_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Button_Login {
            get {
                return ResourceManager.GetString("Login_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create one!.
        /// </summary>
        public static string Login_Label_CreateOne {
            get {
                return ResourceManager.GetString("Login_Label_CreateOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Login_Label_EmailAddress {
            get {
                return ResourceManager.GetString("Login_Label_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have an account?.
        /// </summary>
        public static string Login_Label_NoAccount {
            get {
                return ResourceManager.GetString("Login_Label_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Label_Password {
            get {
                return ResourceManager.GetString("Login_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account was successfully created.
        /// </summary>
        public static string Login_TextBox_CreatedAccount {
            get {
                return ResourceManager.GetString("Login_TextBox_CreatedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email/password cimbination.
        /// </summary>
        public static string Login_TextBox_InvalidCredentials {
            get {
                return ResourceManager.GetString("Login_TextBox_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoffeeTracker - Login.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password which contains at least 6 characters.
        /// </summary>
        public static string PasswordLabeledPasswordBox_ToolTip_ValidPassword {
            get {
                return ResourceManager.GetString("PasswordLabeledPasswordBox_ToolTip_ValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string Registration_Button_Create {
            get {
                return ResourceManager.GetString("Registration_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Have an account?.
        /// </summary>
        public static string Registration_Label_AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("Registration_Label_AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the Login page.
        /// </summary>
        public static string Registration_Label_GoToLogin {
            get {
                return ResourceManager.GetString("Registration_Label_GoToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Could not create account.
        /// </summary>
        public static string Registration_RegistrationFailed {
            get {
                return ResourceManager.GetString("Registration_RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration_Title {
            get {
                return ResourceManager.GetString("Registration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password again.
        /// </summary>
        public static string Registration_Tooltip_ReEnterPassword {
            get {
                return ResourceManager.GetString("Registration_Tooltip_ReEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHF.
        /// </summary>
        public static string Shared_CurrencySwiss {
            get {
                return ResourceManager.GetString("Shared_CurrencySwiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email@example.com.
        /// </summary>
        public static string Shared_Email_Example {
            get {
                return ResourceManager.GetString("Shared_Email_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action you tried to execute is forbidden.
        /// </summary>
        public static string Shared_Forbidden {
            get {
                return ResourceManager.GetString("Shared_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ******.
        /// </summary>
        public static string Shared_Password_Example {
            get {
                return ResourceManager.GetString("Shared_Password_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is currently not available.
        /// </summary>
        public static string Shared_ServiceNotAvailable {
            get {
                return ResourceManager.GetString("Shared_ServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics_Title {
            get {
                return ResourceManager.GetString("Statistics_Title", resourceCulture);
            }
        }
    }
}
